
# Create in-memory database
DATABASE_FILE = 'BalancaInteligente_db.sqlite'
SQLALCHEMY_DATABASE_URI = 'sqlite:///' + DATABASE_FILE
SQLALCHEMY_ECHO = True

# Flask-Security config
DEBUG = True
SECRET_KEY = '123456790'
SECURITY_PASSWORD_HASH = "pbkdf2_sha512"
SECURITY_PASSWORD_SALT = "ATGUOHAELKiubahiughaerGOJAEGj"


# Flask-Security features flags
SECURITY_CONFIRMABLE = False
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_TRACKABLE = False
SECURITY_PASSWORDLESS = False
SECURITY_CHANGEABLE = False

SECURITY_SEND_REGISTER_EMAIL = False

SQLALCHEMY_TRACK_MODIFICATIONS = False
